import {
  ArrowLeft,
  ArrowUp,
  ArrowUpRight,
  ArrowRight,
  DropdownIcon,
  Repost,
} from './_Arrow';
import { Tag } from './_Commerce';
import {
  Pencil,
  Stack,
  GridFour,
  SquaresFour,
  SquareHalf,
  ThreeColumns,
  Eye,
} from './_Design';
import { Plus, Minus, X } from './_Math';
import {
  ImageSquare,
  MusicNotesSimple,
  Newspaper,
  Pause,
  Play,
  Podcast,
  SlidersHorizontal,
} from './_Media';
import {
  NoteBlank,
  Clipboard,
  BookmarkSimple,
  List,
  ListBullets,
  ListNumbers,
  Trash,
  File,
  FileText,
} from './_Office';
import {
  DotsNine,
  LinkSimple,
  MagnifyingGlass,
  Check,
  CheckCircle,
  Bell,
  GearSix,
  LoadingSpin,
  DownloadSimple,
  DotsThree,
  DotsThreeVertical,
  SignOut,
} from './_System';
import { Android, Iphone, Pubky, Twitter, Telegram, Youtube } from './_Social';
import { Clock, Calendar } from './_Time';
import { Globe } from './_Maps';
import {
  UserPlus,
  UserMinus,
  UserRectangle,
  UsersLeft,
  UsersRight,
  Smiley,
} from './_People';
import {
  Asterisk,
  PaperPlaneRight,
  ChatCircleText,
  Broadcast,
  Envelope,
} from './_Communication';
import { Activity } from './_Health';
import { Fire } from './_Weather';
import { Key, Lock, Warning } from './_Security';
import { Synonym, Slashtags, Blocktank, Bitkit, Bitcoin, Tether } from './_Tag';

export const Icon = {
  Android,
  Activity,
  ArrowUp,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Asterisk,
  Bell,
  Bitcoin,
  Bitkit,
  BookmarkSimple,
  Blocktank,
  Broadcast,
  Calendar,
  ChatCircleText,
  Check,
  CheckCircle,
  Clipboard,
  Clock,
  DownloadSimple,
  DropdownIcon,
  DotsNine,
  DotsThree,
  DotsThreeVertical,
  Envelope,
  Eye,
  File,
  FileText,
  Fire,
  GearSix,
  Globe,
  GridFour,
  Iphone,
  ImageSquare,
  Key,
  LinkSimple,
  List,
  ListBullets,
  ListNumbers,
  LoadingSpin,
  Lock,
  MagnifyingGlass,
  Minus,
  MusicNotesSimple,
  Newspaper,
  NoteBlank,
  PaperPlaneRight,
  Pause,
  Pencil,
  Play,
  Plus,
  Podcast,
  Pubky,
  Repost,
  SignOut,
  SlidersHorizontal,
  Synonym,
  Slashtags,
  Smiley,
  SquaresFour,
  SquareHalf,
  Stack,
  Tag,
  Telegram,
  ThreeColumns,
  Twitter,
  Tether,
  Trash,
  UsersLeft,
  UserMinus,
  UsersRight,
  UserPlus,
  UserRectangle,
  Warning,
  Youtube,
  X,
};
