import {
  ArrowLeft,
  ArrowUp,
  ArrowUpRight,
  ArrowRight,
  DropdownIcon,
  Repost,
  CaretRight,
  CaretLeft,
  CaretUp,
  Next,
} from './_Arrow';
import { Tag } from './_Commerce';
import {
  Pencil,
  Ellipse,
  PencilLine,
  Stack,
  GridFour,
  SquaresFour,
  SquareHalf,
  ThreeColumns,
  Eye,
  LineHorizontal,
} from './_Design';
import { Plus, Minus, X, PlusCircle } from './_Math';
import { GitFork } from './_Development';
import { UnitedStates, Spain, Germany, France, Italy } from './_Flag';
import {
  ImageSquare,
  MusicNotesSimple,
  Newspaper,
  Pause,
  Play,
  Podcast,
  SlidersHorizontal,
  SpeakerSimpleSlash,
  SpeakerHigh,
} from './_Media';
import {
  NoteBlank,
  Note,
  Clipboard,
  BookmarkSimple,
  List,
  ListBullets,
  ListNumbers,
  Trash,
  File,
  FileText,
} from './_Office';
import {
  DotsNine,
  Link,
  LinkSimple,
  MagnifyingGlass,
  MagnifyingGlassLeft,
  Check,
  CheckCircle,
  Bell,
  BellSimple,
  GearSix,
  LoadingSpin,
  DownloadSimple,
  DotsThree,
  DotsThreeVertical,
  DotsThreeOutline,
  SignOut,
  SignIn,
} from './_System';
import {
  Android,
  Iphone,
  Pubky,
  Twitter,
  Telegram,
  Youtube,
  Medium,
  Instagram,
  Facebook,
  LinkedIn,
  Github,
  Calendly,
  Twitch,
  TikTok,
  Spotify,
  Discord,
} from './_Social';
import { Clock, Calendar } from './_Time';
import { Globe, GlobeSimple } from './_Maps';
import {
  User,
  UserPlus,
  UserMinus,
  UserRectangle,
  UsersLeft,
  UsersRight,
  UserCircle,
  Smiley,
} from './_People';
import {
  Asterisk,
  PaperPlaneRight,
  ChatCircleText,
  Broadcast,
  Envelope,
} from './_Communication';
import { Activity } from './_Health';
import { Fire } from './_Weather';
import { Key, Lock, Warning, Shield, Question } from './_Security';
import { Synonym, Slashtags, Blocktank, Bitkit, Bitcoin, Tether } from './_Tag';

export const Icon = {
  Android,
  Activity,
  ArrowUp,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Asterisk,
  Bell,
  BellSimple,
  Bitcoin,
  Bitkit,
  BookmarkSimple,
  Blocktank,
  Broadcast,
  Calendar,
  Calendly,
  CaretRight,
  CaretLeft,
  CaretUp,
  ChatCircleText,
  Check,
  CheckCircle,
  Clipboard,
  Clock,
  Discord,
  DownloadSimple,
  DropdownIcon,
  DotsNine,
  DotsThree,
  DotsThreeVertical,
  DotsThreeOutline,
  Envelope,
  Eye,
  Ellipse,
  File,
  FileText,
  France,
  Fire,
  Facebook,
  GearSix,
  GitFork,
  Globe,
  GlobeSimple,
  GridFour,
  Germany,
  Github,
  Instagram,
  Iphone,
  Italy,
  ImageSquare,
  Key,
  LinkSimple,
  LinkedIn,
  Link,
  List,
  ListBullets,
  ListNumbers,
  LoadingSpin,
  LineHorizontal,
  Lock,
  MagnifyingGlass,
  MagnifyingGlassLeft,
  Medium,
  Minus,
  MusicNotesSimple,
  Newspaper,
  Next,
  NoteBlank,
  Note,
  PaperPlaneRight,
  Pause,
  Pencil,
  PencilLine,
  Play,
  Plus,
  PlusCircle,
  Podcast,
  Pubky,
  Question,
  Repost,
  SignOut,
  SignIn,
  SlidersHorizontal,
  Shield,
  Synonym,
  Slashtags,
  Spain,
  Smiley,
  SquaresFour,
  SquareHalf,
  SpeakerSimpleSlash,
  SpeakerHigh,
  Spotify,
  Stack,
  Tag,
  Telegram,
  TikTok,
  ThreeColumns,
  Twitter,
  Twitch,
  Tether,
  Trash,
  UnitedStates,
  User,
  UsersLeft,
  UserMinus,
  UsersRight,
  UserPlus,
  UserCircle,
  UserRectangle,
  Warning,
  Youtube,
  X,
};
