/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_pubkyappfollow_free: (a: number, b: number) => void;
export const __wbg_get_pubkyappfollow_created_at: (a: number) => bigint;
export const __wbg_set_pubkyappfollow_created_at: (a: number, b: bigint) => void;
export const pubkyappfollow_toJson: (a: number) => [number, number, number];
export const __wbg_pubkyappuser_free: (a: number, b: number) => void;
export const pubkyappuser_name: (a: number) => [number, number];
export const pubkyappuser_bio: (a: number) => [number, number];
export const pubkyappuser_image: (a: number) => [number, number];
export const pubkyappuser_links: (a: number) => [number, number];
export const pubkyappuser_status: (a: number) => [number, number];
export const pubkyappuser_toJson: (a: number) => [number, number, number];
export const __wbg_pubkyappuserlink_free: (a: number, b: number) => void;
export const pubkyappuser_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => number;
export const pubkyappuserlink_new: (a: number, b: number, c: number, d: number) => number;
export const __wbg_meta_free: (a: number, b: number) => void;
export const meta_id: (a: number) => [number, number];
export const meta_path: (a: number) => [number, number];
export const meta_url: (a: number) => [number, number];
export const __wbg_pubkyappbuilder_free: (a: number, b: number) => void;
export const __wbg_followresult_free: (a: number, b: number) => void;
export const followresult_meta: (a: number) => number;
export const followresult_follow: (a: number) => number;
export const __wbg_userresult_free: (a: number, b: number) => void;
export const userresult_user: (a: number) => number;
export const userresult_meta: (a: number) => number;
export const pubkyappbuilder_new: (a: number, b: number) => number;
export const pubkyappbuilder_createFollow: (a: number, b: number, c: number) => [number, number, number];
export const pubkyappbuilder_createUser: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: any, i: number, j: number) => [number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
