import {
  ArrowLeft,
  ArrowsLeftRight,
  ArrowUp,
  ArrowUpRight,
  ArrowRight,
  DropdownIcon,
  Repost,
  CaretRight,
  CaretLeft,
  CaretUp,
  Next
} from './_Arrow';
import { Tag, Handbag } from './_Commerce';
import {
  Pencil,
  Ellipse,
  PencilLine,
  Stack,
  GridFour,
  SquaresFour,
  SquareHalf,
  ThreeColumns,
  Eye,
  EyeSlash,
  LineHorizontal
} from './_Design';
import { Plus, Minus, X, PlusCircle } from './_Math';
import { GitFork } from './_Development';
import { UnitedStates, Spain, Germany, France, Italy } from './_Flag';
import {
  ImageSquare,
  MusicNotesSimple,
  Newspaper,
  Pause,
  Play,
  Podcast,
  SlidersHorizontal,
  SpeakerSimpleSlash,
  SpeakerHigh
} from './_Media';
import {
  NoteBlank,
  Note,
  Clipboard,
  BookmarkSimple,
  Bookmarks,
  List,
  ListBullets,
  ListNumbers,
  Trash,
  File,
  FileText,
  Copy,
  TextAlignLeft,
  TextAlignRight,
  TextAlignCenter
} from './_Office';
import {
  DotsNine,
  Link,
  LinkSimple,
  MagnifyingGlass,
  MagnifyingGlassLeft,
  Check,
  CheckCircle,
  Bell,
  BellSimple,
  GearSix,
  HomeIndicator,
  LoadingSpin,
  Lightbulb,
  DownloadSimple,
  DotsThree,
  DotsThreeVertical,
  DotsThreeOutline,
  UploadSimple,
  SignOut,
  SignIn,
  XCircle
} from './_System';
import {
  Android,
  Iphone,
  Pubky,
  Twitter,
  Telegram,
  Youtube,
  Medium,
  Instagram,
  Facebook,
  LinkedIn,
  Github,
  Calendly,
  Twitch,
  TikTok,
  Spotify,
  Discord
} from './_Social';
import { Clock, Calendar } from './_Time';
import { House, Globe, GlobeSimple, Crosshair } from './_Maps';
import {
  User,
  UserPlus,
  UserMinus,
  UserRectangle,
  UsersLeft,
  UsersRight,
  UserCircle,
  Smiley,
  SmileySad,
  Hand,
  Pedestrian
} from './_People';
import { Asterisk, PaperPlaneRight, ChatCircleText, Broadcast, Envelope, Megaphone } from './_Communication';
import { Activity } from './_Health';
import { Fire } from './_Weather';
import {
  Key,
  Lock,
  LockKey,
  LockSimple,
  LockKeyOpen,
  Warning,
  Shield,
  Question,
  Flag,
  WarningOctagon,
  ShieldWarning
} from './_Security';
import { Synonym, Blocktank, Bitkit, Bitcoin, Tether, PubkyIcon } from './_Tag';

export const Icon = {
  Android,
  Activity,
  ArrowUp,
  ArrowLeft,
  ArrowsLeftRight,
  ArrowRight,
  ArrowUpRight,
  Asterisk,
  Bell,
  BellSimple,
  Bitcoin,
  Bitkit,
  BookmarkSimple,
  Bookmarks,
  Blocktank,
  Broadcast,
  Calendar,
  Calendly,
  CaretRight,
  CaretLeft,
  CaretUp,
  ChatCircleText,
  Check,
  CheckCircle,
  Clipboard,
  Clock,
  Copy,
  Crosshair,
  Discord,
  DownloadSimple,
  DropdownIcon,
  DotsNine,
  DotsThree,
  DotsThreeVertical,
  DotsThreeOutline,
  Envelope,
  Eye,
  EyeSlash,
  Ellipse,
  File,
  FileText,
  Flag,
  France,
  Fire,
  Facebook,
  GearSix,
  GitFork,
  Globe,
  GlobeSimple,
  GridFour,
  Germany,
  Github,
  Instagram,
  House,
  Iphone,
  Italy,
  Hand,
  Handbag,
  HomeIndicator,
  ImageSquare,
  Key,
  LinkSimple,
  LinkedIn,
  Link,
  List,
  ListBullets,
  ListNumbers,
  LoadingSpin,
  LineHorizontal,
  Lock,
  LockKey,
  LockKeyOpen,
  LockSimple,
  Lightbulb,
  MagnifyingGlass,
  MagnifyingGlassLeft,
  Medium,
  Megaphone,
  Minus,
  MusicNotesSimple,
  Newspaper,
  Next,
  NoteBlank,
  Note,
  PaperPlaneRight,
  Pause,
  Pedestrian,
  Pencil,
  PencilLine,
  Play,
  Plus,
  PlusCircle,
  Podcast,
  Pubky,
  PubkyIcon,
  Question,
  Repost,
  SignOut,
  SignIn,
  SlidersHorizontal,
  Shield,
  ShieldWarning,
  Synonym,
  Spain,
  Smiley,
  SmileySad,
  SquaresFour,
  SquareHalf,
  SpeakerSimpleSlash,
  SpeakerHigh,
  Spotify,
  Stack,
  Tag,
  Telegram,
  TextAlignLeft,
  TextAlignRight,
  TextAlignCenter,
  TikTok,
  ThreeColumns,
  Twitter,
  Twitch,
  Tether,
  Trash,
  UnitedStates,
  UploadSimple,
  User,
  UsersLeft,
  UserMinus,
  UsersRight,
  UserPlus,
  UserCircle,
  UserRectangle,
  Warning,
  WarningOctagon,
  Youtube,
  X,
  XCircle
};
