name: e2e-test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [firefox] # [chrome, firefox]

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          path: pubky-app

      - name: Checkout pubky-docker
        uses: actions/checkout@v4
        with:
          repository: pubky/pubky-docker
          ref: catch-21/update
          path: pubky-docker
          submodules: true
          token: ${{ secrets.READ_REPOS }}
          # cannot use ssh-key (deploy key) for private submodules due to the
          # limitation where only a single key can be used per repo checkout
          # see https://github.com/actions/checkout/issues/183

      - name: Modify pubky-docker docker-compose.yml
        working-directory: pubky-docker/development
        run: |
          YQ_BINARY=yq_linux_amd64
          YQ_VERSION=v4.44.3
          wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY}.tar.gz -O - | tar xz && sudo mv ${YQ_BINARY} /usr/bin/yq
          yq -i 'del(.services.pkarr)' docker-compose.yml
          yq -i 'del(.services.client)' docker-compose.yml
          yq -i 'del(.services.homeserver.depends_on)' docker-compose.yml

      - name: Modify homeserver.config.toml
        working-directory: pubky-docker/development
        run: sed -i 's/secret_key = "0123000000000000000000000000000000000000000000000000000000000000"/secret_key = "${{ secrets.HOMESERVER_SECRET_KEY }}"/' homeserver.config.toml

      # reduce neo4j memory to prevent
      # ERROR Invalid memory configuration - exceeds physical memory. Check the configured values for server.memory.pagecache.size and server.memory.heap.max_size
      - name: Modify neo4j.env
        working-directory: pubky-docker/development
        run: |
          sed -i 's/NEO4J_server_memory_pagecache_size=2G/NEO4J_server_memory_pagecache_size=1G/' neo4j.env
          sed -i 's/NEO4J_server_memory_heap_initial__size=4G/NEO4J_server_memory_heap_initial__size=1G/' neo4j.env
          sed -i 's/NEO4J_server_memory_heap_max__size=8G/NEO4J_server_memory_heap_max__size=2G/' neo4j.env

      - name: Build and run pubky-docker
        working-directory: pubky-docker/development
        run: docker compose up -d

      - name: Wait for pubky-docker to start
        run: |
          PORT=8080
          MAX_WAIT=300     # Maximum wait time in seconds (5 minutes)
          WAIT_INTERVAL=5  # Interval between checks in seconds
          ELAPSED=0

          while ! curl -s http://localhost:$PORT; do
            if [ $ELAPSED -ge $MAX_WAIT ]; then
              echo "Service did not start within 5 minutes."
              exit 1
            fi
            echo "Waiting for service on port $PORT to be ready... ($ELAPSED seconds elapsed)"
            sleep $WAIT_INTERVAL
            ELAPSED=$((ELAPSED + WAIT_INTERVAL))
          done

          echo "Service is ready."

      - name: Build pubky-app frontend
        working-directory: pubky-app
        run: |
          echo "NEXT_PUBLIC_HOMESERVER=${{ secrets.HOMESERVER_PUBKY }}
          NEXT_PUBLIC_NEXUS=http://localhost:8080
          NEXT_PUBLIC_TESTNET=false
          NEXT_PUBLIC_DEFAULT_HTTP_RELAY=https://demo.httprelay.io/link/
          BASE_URL_SUPPORT=${{ secrets.BASE_URL_SUPPORT }}
          SUPPORT_API_ACCESS_TOKEN=${{ secrets.SUPPORT_API_ACCESS_TOKEN }}
          SUPPORT_ACCOUNT_ID=1" > .env
          npm install

      - name: Run e2e tests (${{ matrix.browser }})
        uses: cypress-io/github-action@v6
        env:
          DEBUG: '@cypress/github-action'
        with:
          working-directory: pubky-app/apps/web-e2e
          config-file: cypress.config.ts
          spec: src/e2e/**/*.cy.ts
          browser: ${{ matrix.browser }}
          headed: false
          summary-title: ${{ matrix.browser }}
          install: false
          start: npm run start:prod
          wait-on: 'http://localhost:4200'
          wait-on-timeout: 180

      - name: Upload ${{ matrix.browser }} screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.browser }}
          path: pubky-app/dist/cypress/apps/web-e2e/screenshots

      - name: Upload ${{ matrix.browser }} videos
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: videos-${{ matrix.browser }}
          path: pubky-app/dist/cypress/apps/web-e2e/videos

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2